---
- name: Update Yum
  yum: update_cache=yes

- name: Change hostname
  ansible.builtin.shell: hostname kube-master-node

- name: Download Install Script
  ansible.builtin.get_url:
    url: "https://get.rke2.io"
    dest: "/tmp/install.sh"

- name: Make executable
  ansible.builtin.shell: chmod +x /tmp/install.sh

- name: Install RKE2
  ansible.builtin.shell: /tmp/install.sh

- name: Enable and Start RKE2
  service:
    name: rke2-server.service
    state: started
    enabled: true

- name: Disable firewalld
  service:
    name: firewalld.service
    state: stopped
    enabled: false
