- name: Clone a VM from Template
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/default.yaml
  tasks:

    - name: Gather a virtual machine info
      vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter }}"
        name: "kube-worker-4"
      register: gather_vm_info

    - name: Display the first interface set IP Address of a virtual machine
      debug:
        msg: >-
          {{ gather_vm_info.instance.hw_eth0.ipaddresses
            | map('ansible.utils.ipaddr', 'ipv4')
            | select('!=', false)
            | list
            | first
          }}

