apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: istio-system
spec:
  secretName: argocd-tls
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - argocd.sdc.cpp
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
